# coding: utf-8

# Http status code
# NOTE: Need copy http code from openai lib.
HTTP_CODE_INVALID_REQUEST = 400
HTTP_CODE_AUTHENTICATION = 401
HTTP_CODE_PERMISSION = 403
HTTP_CODE_NOTFOUND = 404
HTTP_CODE_TRY_AGAIN = 409
HTTP_CODE_UNPROCESSABLE = 422
